# Introduction to Pandas

Resources:
- [Pandas User Guide (10 min)](https://pandas.pydata.org/docs/user_guide/10min.html)
- [Python for Data Analysis by Wes McKinney](https://wesmckinney.com/book/)

*Why use Pandas?*

While NumPy is excellent for numerical matrices (homogeneous data), Pandas is designed for tabular data (heterogeneous data). 
Think of a DataFrame as a NumPy array with labels, or an Excel sheet, allowing you to mix strings, integers, and floats in one table.

In [1]:
import numpy as np
import pandas as pd

In [2]:
# why pandas? it's useful!
pd.read_html('https://arghyadutta.github.io/notebooks/excelShortcuts.html')[0]

,Shortcut,Action
0,Control + U,Edit the active cell without overwriting
1,Type directly,Replace cell contents
2,Return,Enter and move down
3,Shift + Return,Enter and move up
4,Tab,Enter and move right
5,Shift + Tab,Enter and move left
6,Control + Return,Enter without moving
7,Escape,Cancel editing
8,Control + Option + Return,Insert line break inside a cell (sometimes Opt...

## Pandas Series

A 1D labeled array that can hold any data type (ints, floats, strings, objects).

- Like a NumPy 1D array, but with an index
- Each value is accessed by its label, not just position
- Supports vectorized operations and alignment by index

In [3]:
foo = [10, 20, 30]
foo[0]

10

In [4]:
# s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])

s = pd.Series({'a':10,'b':20,'c':30})

# the values of a series are returned as numpy arrays
print(s, s.values, type(s.values))

# vectorized operation (often intuitive)
s + 5

a    10
b    20
c    30
dtype: int64 [10 20 30] <class 'numpy.ndarray'>

a    15
b    25
c    35
dtype: int64

## DataFrame

2D, labeled tabular data structure.

- Rows and columns both have indexes
- Columns can hold different data types
- Supports vectorized operations, alignment, grouping, merging

![](Pandas_dataframe.png)

[Source: Wikimedia commons](https://commons.wikimedia.org/wiki/File:Pandas_dataframe.png)

In [5]:
# defining a dataframe from a dictionary
data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 35],
    'score': [88.5, 92.0, 79.5]
}

df = pd.DataFrame(data)
print("--- Original DataFrame ---")
print(df)

# print("the structure of your data")
# df.info()

print("get some statistical values")
print(df.describe())

print(f"\nColumns: {df.columns.tolist()}")

--- Original DataFrame ---
      name  age  score
0    Alice   25   88.5
1      Bob   30   92.0
2  Charlie   35   79.5
get some statistical values
        age      score
count   3.0   3.000000
mean   30.0  86.666667
std     5.0   6.448514
min    25.0  79.500000
25%    27.5  84.000000
50%    30.0  88.500000
75%    32.5  90.250000
max    35.0  92.000000

Columns: ['name', 'age', 'score']

## Indexing: loc vs iloc

- `.loc`: Label-based (uses names/labels)
- `.iloc`: Integer-position based (uses 0, 1, 2...)

In [6]:
# row
df
df.loc[0]['name'] # label-based
df.iloc[0] # position-based

# column
df.iloc[:,1]
df["age"]
df[["name", "score"]]

      name  age  score
0    Alice   25   88.5
1      Bob   30   92.0
2  Charlie   35   79.5

'Alice'

name     Alice
age         25
score     88.5
Name: 0, dtype: object

0    25
1    30
2    35
Name: age, dtype: int64

0    25
1    30
2    35
Name: age, dtype: int64

      name  score
0    Alice   88.5
1      Bob   92.0
2  Charlie   79.5

In [7]:
# boolean indexing works as in numpy
df
# df[df['age'] > 28]
df[df['score'] > 90]
df.query("score >= 90")

# more complex logical operation

print(df[(df['age'] > 25) & (df['score'] > 80)])

      name  age  score
0    Alice   25   88.5
1      Bob   30   92.0
2  Charlie   35   79.5

  name  age  score
1  Bob   30   92.0

  name  age  score
1  Bob   30   92.0

  name  age  score
1  Bob   30   92.0

## Operations and column manipulations

In [8]:
# New column
df
df["passed"] = df["score"] >= 85
df["old"] = df["age"] > 25
df

# Vectorized (preferred)
df["age_squared"] = df["age"] ** 2

df.sort_values("age", ascending=False)

      name  age  score
0    Alice   25   88.5
1      Bob   30   92.0
2  Charlie   35   79.5

      name  age  score  passed    old
0    Alice   25   88.5    True  False
1      Bob   30   92.0    True   True
2  Charlie   35   79.5   False   True

      name  age  score  passed    old  age_squared
2  Charlie   35   79.5   False   True         1225
1      Bob   30   92.0    True   True          900
0    Alice   25   88.5    True  False          625

In [9]:

df.head(2) #first two rows
df.tail(2) # last two rows

# how many unique values in a particular column?
df.value_counts("passed")

    name  age  score  passed    old  age_squared
0  Alice   25   88.5    True  False          625
1    Bob   30   92.0    True   True          900

      name  age  score  passed   old  age_squared
1      Bob   30   92.0    True  True          900
2  Charlie   35   79.5   False  True         1225

passed
True     2
False    1
Name: count, dtype: int64

## Missing Data

In [10]:
# # uncomment, and run. explore more!
# df_nan = df.copy()
# df_nan.loc[1, 'score'] = np.nan
# df_nan
# df_nan.isna()
# df_nan.fillna(df_nan['score'].mean())

## GroupBy

In [11]:
df['department'] = ['CS', 'Math', 'CS']
df
df.groupby('department')['score'].mean()

      name  age  score  passed    old  age_squared department
0    Alice   25   88.5    True  False          625         CS
1      Bob   30   92.0    True   True          900       Math
2  Charlie   35   79.5   False   True         1225         CS

department
CS      84.0
Math    92.0
Name: score, dtype: float64

## Merge

In [12]:
info = pd.DataFrame({
    'name': ['Charlie','Alice', 'Bob'],
    'city': ['Chennai','Delhi', 'Mumbai']
})
df
info
pd.merge(df, info, on='name')

      name  age  score  passed    old  age_squared department
0    Alice   25   88.5    True  False          625         CS
1      Bob   30   92.0    True   True          900       Math
2  Charlie   35   79.5   False   True         1225         CS

      name     city
0  Charlie  Chennai
1    Alice    Delhi
2      Bob   Mumbai

      name  age  score  passed    old  age_squared department     city
0    Alice   25   88.5    True  False          625         CS    Delhi
1      Bob   30   92.0    True   True          900       Math   Mumbai
2  Charlie   35   79.5   False   True         1225         CS  Chennai

## Data read and write

In [13]:
df.to_csv("students.csv", index=False)
df.to_excel("students.xlsx",index=False)

In [14]:
new_df = pd.read_excel('students.xlsx')
new_df

      name  age  score  passed    old  age_squared department
0    Alice   25   88.5    True  False          625         CS
1      Bob   30   92.0    True   True          900       Math
2  Charlie   35   79.5   False   True         1225         CS